### PR TITLE
Added Celery Pytest Plugin

### PR DESCRIPTION
**Pull request by Nusnus**

### CODE REVIEW

**Comment by Nusnus** [comment]
@svfat

**Comment by svfat** [comment]
Thanks @Nusnus !
I am going to fix github pipeline, and merge it very soon

**Comment by Nusnus** [comment]
> Thanks @Nusnus ! I am going to fix github pipeline, and merge it very soon

Awesome - thank you!

**Comment by svfat** [comment]
@Nusnus could you pull the latest changes from main and push again please?

**Comment by Nusnus** [comment]
> @Nusnus could you pull the latest changes from main and push again please?

Done.

By the way, you can add an option in the repo’s settings to have it done easily from the PR itself:
CleanShot 2024-05-09 at 13 23 56

@svfat

**Comment by svfat** [comment]
Merged, thank you for contributing!

**Pull request merged**
